spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: embedded

security:
  jwt:
    secret-key: eyJhbGciOiJIeyJzdWIilowafgfaoTazAGa
    expiration-time: 36000000
